# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_parcelysearchform.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ParcelySearchForm(object):
    def setupUi(self, ParcelySearchForm):
        ParcelySearchForm.setObjectName("ParcelySearchForm")
        ParcelySearchForm.resize(269, 168)
        self.gridLayout = QtWidgets.QGridLayout(ParcelySearchForm)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(ParcelySearchForm)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.parCisloLineEdit = QtWidgets.QLineEdit(ParcelySearchForm)
        self.parCisloLineEdit.setInputMask("")
        self.parCisloLineEdit.setObjectName("parCisloLineEdit")
        self.gridLayout.addWidget(self.parCisloLineEdit, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(ParcelySearchForm)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.typParcelyCombo = QtWidgets.QComboBox(ParcelySearchForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typParcelyCombo.sizePolicy().hasHeightForWidth())
        self.typParcelyCombo.setSizePolicy(sizePolicy)
        self.typParcelyCombo.setObjectName("typParcelyCombo")
        self.typParcelyCombo.addItem("")
        self.typParcelyCombo.addItem("")
        self.typParcelyCombo.addItem("")
        self.gridLayout.addWidget(self.typParcelyCombo, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(ParcelySearchForm)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.druhPozemkuCombo = QtWidgets.QComboBox(ParcelySearchForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.druhPozemkuCombo.sizePolicy().hasHeightForWidth())
        self.druhPozemkuCombo.setSizePolicy(sizePolicy)
        self.druhPozemkuCombo.setObjectName("druhPozemkuCombo")
        self.gridLayout.addWidget(self.druhPozemkuCombo, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.lvParcelyLineEdit = QtWidgets.QLineEdit(ParcelySearchForm)
        self.lvParcelyLineEdit.setObjectName("lvParcelyLineEdit")
        self.gridLayout.addWidget(self.lvParcelyLineEdit, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(ParcelySearchForm)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)

        self.retranslateUi(ParcelySearchForm)
        QtCore.QMetaObject.connectSlotsByName(ParcelySearchForm)

    def retranslateUi(self, ParcelySearchForm):
        _translate = QtCore.QCoreApplication.translate
        ParcelySearchForm.setWindowTitle(_translate("ParcelySearchForm", "Form"))
        self.label_3.setText(_translate("ParcelySearchForm", "Parcelní číslo :"))
        self.label_5.setText(_translate("ParcelySearchForm", "Typ parcely:"))
        self.typParcelyCombo.setItemText(0, _translate("ParcelySearchForm", "libovolný"))
        self.typParcelyCombo.setItemText(1, _translate("ParcelySearchForm", "pozemková"))
        self.typParcelyCombo.setItemText(2, _translate("ParcelySearchForm", "stavební"))
        self.label_6.setText(_translate("ParcelySearchForm", "Druh pozemku:"))
        self.label.setText(_translate("ParcelySearchForm", "LV:"))
